- path: output/reject_domain.mrs
  format: mrs
  behavior: domain
  upstream:
    anti_list:
      type: http
      behavior: classical
      format: text
      url: https://raw.githubusercontent.com/Egeonn/kkk/refs/heads/release/anti_list.txt
- path: output/reject_ip.mrs
  format: mrs
  behavior: ipcidr
  upstream:
    anti_list:
      type: http
      behavior: classical
      format: text
      url: https://raw.githubusercontent.com/Egeonn/kkk/refs/heads/release/anti_list.txt
- path: output/Global.mrs
  format: mrs
  behavior: domain
  upstream:
    Global:
      type: http
      behavior: classical
      format: text
      url: https://raw.githubusercontent.com/Egeonn/kkk/refs/heads/release/Global.txt
- path: output/cn_ip.mrs
  format: mrs
  behavior: ipcidr
  upstream:
    anti_list:
      type: http
      behavior: classical
      format: text
      url: https://raw.githubusercontent.com/Egeonn/kkk/refs/heads/release/cn_ip.txt
